added a design
2yar/Podranok pull request #15
Opened 2018-04-18 15:18 UTC by gidpoiiohika

2018-05-21 14:51 UTC, ezhenezhen requested changes
я так розумію - куча файлів лишніх, типу картинок? взагалі такі великі пулл реквести треба не робити. одна задача - один пулл реквест. їх важко перевіряти.

2018-05-21 14:51 UTC, ezhenezhen commented on app/controllers/articles_controller.rb
> +        format.html { redirect_to @article, notice: 'Article успешно создана.' }
уже б робив на рус чи на англ - однаково. чого на обох мовах? плюс у тебе чось файли російською називаються - треба зробить англ

2018-05-21 14:51 UTC, ezhenezhen commented on app/controllers/carts_controller.rb
> +  skip_before_action :authenticate_user!
точно не треба перевірять юзера?

2018-05-21 14:51 UTC, ezhenezhen commented on app/models/product.rb
> +    where("name LIKE ? OR price LIKE ?", "%#{search}%", "%#{search}%")
а для чого тут інтерполяція?

2018-05-21 14:51 UTC, ezhenezhen commented on app/models/user.rb
> +         :omniauthable, :omniauth_providers => [:facebook]
може треба новий синтаксис для хеша використовувати?

2018-05-21 14:51 UTC, ezhenezhen commented on app/views/carts/show.slim
> +  = button_to 'Очистить корзину', @cart, method: :delete, data: { confirm: 'Вы уверен?' }
ы

2018-05-21 14:51 UTC, ezhenezhen commented on config/initializers/devise.rb
> +  config.omniauth :facebook, "248556039026232", "5c2060ef8e1a84bf752b16ae936047c1", callback_url: "http://localhost:3000/users/auth/facebook/callback"
паролі/токени не хранять в репозиторіях. хто хоч може зайти і використати їх тут. треба почитать як зберагіть паролі в рельсах. наприклад, ENV змінні заюзать. хоча це може бути зараз не актуальним...

2018-05-22 07:22 UTC, gidpoiiohika commented on app/controllers/carts_controller.rb
> +  skip_before_action :authenticate_user!
Ну на всех сайтах "Охотничих" я не разу не видел что бы нужно было зарегистрироваться что бы добавить товар в корзину, не знаю как правильно.

2018-05-23 10:36 UTC, merged